project:
  type: website
  output-dir: docs

website:
  title: "PB"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - href: reflection.qmd
        text: Reflection
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
    right: []
    background: primary
    foreground: light
  page-footer:
    left: "© 2026 Priyadharshini Balaji"
    right:
      - icon: github
        href: https://github.com/priyadharshini-code-beep
      - icon: linkedin
        href: https://www.linkedin.com/in/priyadharshini-balaji-66a361224/

format:
  html:
    theme: [cosmo, styles.scss]
    css: styles.css
    toc: false
    smooth-scroll: true
